{{/*
==========================================================================
CAST Imaging MCP Server - Persistent Volume Claims Template
==========================================================================
This template creates a single Persistent Volume Claim (PVC) for the CAST Imaging MCP Server.
The PVC provides persistent storage that survives pod restarts and rescheduling.

STORAGE APPROACH:
- Single PVC for all storage needs (logs and data)
- Organized with subdirectories: /app/storage/logs and /app/storage/data
- Init container creates directory structure during pod startup

STORAGE CONFIGURATION:
- Uses dynamic provisioning with specified storage class
- Supports cloud-specific storage classes (e.g., "standard-rwo" for GCP)
- Setting storageClass to "-" uses default cluster storage class

TEMPLATE VARIABLES:
- .Values.persistence.enabled: Controls PVC creation
- .Values.persistence.size: Storage size (e.g., "5Gi")
- .Values.persistence.accessMode: Access mode (typically "ReadWriteOnce")
- .Values.persistence.storageClass: Storage class for dynamic provisioning
==========================================================================
*/}}

{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cast-imaging-mcp.fullname" . }}-storage
  labels:
    {{- include "cast-imaging-mcp.labels" . | nindent 4 }}
    component: storage
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}